export const POKEMON_TYPES_COLOR_MAP = {
  normal: '#ccc',
  fighting: '',
  flying: '',
  poison: '#b97fc9',
  ground: '',
  rock: '',
  bug: '',
  ghost: '',
  steel: '',
  fire: '',
  water: '',
  grass: '#9bcc50',
  electric: '',
  psychic: '',
  ice: '',
  dragon: '',
  dark: '',
  fairy: '',
  unknown: '',
  shadow: '',
}
